apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: line
  namespace: line
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: line
    spec:
      containers:
      - name: line
        image: aliayubkhan/susi_linebot:latest
        imagePullPolicy: Always
        env: 
        - name: CHANNEL_ACCESS_TOKEN
          value: "hYLoXRWvzVUNc5DtZSRWEhjRKaT2EmOc/d4f1VcowrBddxl2IY1TkHOZn/QHJLxNZEK4nQRrwLlsiKg2f6roBbMDk/4WB4WSqEymrmSwv01oXhgtiZmUXMyGlqXSW0yDdsfUKRWStKUgNdn//a7SYgdB04t89/1O/w1cDnyilFU="
        - name: CHANNEL_SECRET
          value: "63ab12be6cb1f0c8fc3dafd42455e2fd"
        ports:
        - containerPort: 8080

